### ISSUE TITLE
Attribute-indentation error

### ISSUE THREAD

**Issue by musaffa** [simplabs/emblem-migrator#3]
```haml
% Display::Tag::Display [
  @tag=tag
  @params=params
  @page=page
  @perPage=perPage
]
```
gets converted to

```hbs
<Display::Tag::Display
  @tag={{tag}}
  @params={{params}}
  @page={{page}}
  @perPage={{perPage}}
 />
```
`/>` is not properly indented. So the linter shows this error massage: `attribute-indentation: Incorrect indentation of close bracket '>'`

**Comment by Turbo87** [comment]
we use the Handlebars mode of http://prettier.io/ for the formatting and that is not compatible with the indentation rule of ember-template-lint. IMHO the indentation rule of ember-template-lint should never have been enabled by default.

this is not something we are going to fix. it should be fixed either in ember-template-lint or in prettier.
